// Wire-schema docs generator (dev-only, no runtime cost).
// Usage: bun run scripts/generate-wire-schema.ts  (npm script: docs:wire)
// Emits docs/wire-schema.json from the frozen v1 frame schemas.
//
// Engine note (LIBRARIES.md §7): the spec'd `zod-to-json-schema@3` (devDependency)
// cannot convert these schemas: it dispatches on `schema._def.typeName`
// (zod v3 internals), but zod v4 (this repo: ^4.6.1) exposes `_def.type` instead,
// so every schema degrades to `{}` (verified: object + discriminatedUnion both
// emit empty definitions; `zod/v4/classic` subpath does not exist in 4.6.1).
// The script therefore uses zod 4's built-in `z.toJSONSchema()` as the working
// alternative. Upgrade path: if zod-to-json-schema ships real zod-4 support,
// swap the two `z.toJSONSchema(...)` calls below for `zodToJsonSchema(...)`;
// the LogFrame.chunk `.describe()` in ../orpc-contract/src/machine-frames.ts flows
// into either engine (zod-to-json-schema copies it via its `addMeta` step).
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { MachineFrameSchema, ServerFrameSchema } from "@uma/orpc-contract";
import { z } from "zod";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outPath = join(root, "docs", "wire-schema.json");

const machineJson = z.toJSONSchema(MachineFrameSchema, {
	unrepresentable: "any",
}) as Record<string, unknown>;
const serverJson = z.toJSONSchema(ServerFrameSchema, {
	unrepresentable: "any",
}) as Record<string, unknown>;

function assert(cond: unknown, msg: string): asserts cond {
	if (!cond) throw new Error(`generate-wire-schema FAIL: ${msg}`);
}

// The LogFrame.chunk cap is enforced by a byte-length refine (TextEncoder,
// UTF-8 bytes — not z.max UTF-16 units). The human-readable cap must survive
// into the docs; fail loudly if the engine ever drops it.
const machineVariants = (machineJson.oneOf ?? machineJson.anyOf) as
	| Record<string, unknown>[]
	| undefined;
assert(
	Array.isArray(machineVariants) && machineVariants.length > 0,
	"MachineFrame schema has no variants",
);
const logVariant = machineVariants?.find(
	(v) =>
		(v.properties as Record<string, Record<string, unknown>> | undefined)?.t
			?.const === "log",
);
const chunkDesc = (
	(logVariant?.properties as Record<string, Record<string, unknown>>)?.chunk as
		| Record<string, unknown>
		| undefined
)?.description;
assert(
	typeof chunkDesc === "string" &&
		chunkDesc.includes("UTF-8") &&
		chunkDesc.includes("256KB"),
	"LogFrame.chunk description missing UTF-8 bytes cap note",
);

const serverVariants = (serverJson.oneOf ?? serverJson.anyOf) as
	| Record<string, unknown>[]
	| undefined;
assert(
	Array.isArray(serverVariants) && serverVariants.length > 0,
	"ServerFrame schema has no variants",
);

const doc = {
	$comment:
		"Generated by scripts/generate-wire-schema.ts (bun run docs:wire). Do not edit by hand.",
	$schema: "https://json-schema.org/draft/2020-12/schema",
	MachineFrame: machineJson,
	protocol: "v1",
	ServerFrame: serverJson,
};

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, `${JSON.stringify(doc, null, 2)}\n`);
console.log(`[wire-schema] wrote ${outPath}`);
